import { test, expect } from '@playwright/test';
test('Published GitHub Pages loads its routes, all 45 fields and local assets', async ({ page }) => {
  await page.goto('https://haianhta115-a11y.github.io/carelink-community/');
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Kết nối yêu thương');
  await page.getByRole('button', { name: 'Khám phá tất cả lĩnh vực', exact: true }).click();
  await expect(page.locator('.expanded-catalog .category-card')).toHaveCount(45);
  await expect.poll(() => page.locator('.hero-photo img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBeTruthy();
  await page.getByRole('link', { name: 'Đăng nhập', exact: true }).first().click();
  await expect(page).toHaveURL(/#\/login$/);
  await expect(page.locator('#email')).toBeVisible();
  await page.locator('#email').fill('admin@carelink.vn');
  await page.locator('#password').fill('Admin@12345');
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click();
  await expect(page).toHaveURL(/#\/admin$/);
  await expect(page.getByRole('heading', { level: 1 }).first()).toBeVisible();
  await page.goto('https://haianhta115-a11y.github.io/carelink-community/#/admin/users');
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Quản lý tài khoản');
  await page.goto('https://haianhta115-a11y.github.io/carelink-community/#/admin/requests');
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Kiểm duyệt');
});
